apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: config-sample
spec:
  groups:
    - name: ops_manager_location
      title: Mongo Cloud / Ops Manager Configuration
      items:
        - name: ops_manager_deploy_or_existing
          title: Deploy Ops Manager or use existing / cloud manager
          type: select_one
          default: ops_manager_new
          items:
            - name: ops_manager_existing
              title: Use Existing Ops Manager / Cloud Manager
            - name: ops_manager_new
              title: Deploy Ops Manager to this cluster

    # Config when deploying opsmanager to the cluster
    - name: ops_manager_new
      title: Local OpsManager
      items:
        - name: om_username
          title: Username
          type: text
          default: "admin@mongodb.com"
          required: true
          when: "repl{{ ConfigOptionEquals `ops_manager_deploy_or_existing` `ops_manager_new` }}"
        - name: om_password
          title: Password
          help_text: Choose a strong password here, the service will not accept weak passwords
          type: password
          default: "MongoDB12345%"
          required: true
          when: "repl{{ ConfigOptionEquals `ops_manager_deploy_or_existing` `ops_manager_new` }}"
        - name: om_publicapikey
          title: Public API Key
          type: text
          default: "MongoDB12345%"
          required: true
          when: "repl{{ ConfigOptionEquals `ops_manager_deploy_or_existing` `ps_manager_new` }}"
        - name: om_port
          title: Port
          type: text
          default: "8080"
          required: true
          when: "repl{{ ConfigOptionEquals `ops_manager_deploy_or_existing` `ops_manager_new` }}"
        - name: om_firstname
          title: First Name
          type: text
          default: "Joe"
          required: true
          when: "repl{{ ConfigOptionEquals `ops_manager_deploy_or_existing` `ops_manager_new` }}"
        - name: om_lastname
          title: Last Name
          type: text
          default: "McMongo"
          required: true
          when: "repl{{ ConfigOptionEquals `ops_manager_deploy_or_existing` `ops_manager_new` }}"
        - name: om_service_type
          title: External Connectivity for Ops Manager
          type: select_one
          default: om_service_type_clusterip
          when: "repl{{ ConfigOptionEquals `ops_manager_deploy_or_existing` `ops_manager_new` }}"
          items:
            - name: om_service_type_clusterip
              title: None (ClusterIP only)
            - name: om_service_type_nodeport
              title: NodePort
            - name: om_service_type_loadbalancer
              title: LoadBalancer
        - name: om_node_port
          title: NodePort
          type: text
          required: true
          when: "repl{{ ConfigOptionEquals `om_service_type` `om_service_type_nodeport`}}"
          help_text: NodePort should be between 30000-32767

    # config when an existing ops manager
    - name: ops_manager_cloud
      title: Existing Ops Manager / Cloud Manager
      items:
        - name: mongo_api_public_key
          help_text: Cloud Manager can generate a new key [here](https://account.mongodb.com/account/login)
          title: MongoDB API Public Key
          type: text
          required: true
          when: "repl{{ ConfigOptionEquals `ops_manager_deploy_or_existing` `ops_manager_existing`}}"
        - name: mongo_api_private_key
          title: MongoDB API Private Key
          type: password
          required: true
          when: "repl{{ ConfigOptionEquals `ops_manager_deploy_or_existing` `ops_manager_existing`}}" 

        - name: mongo_ops_manager_project_new_or_existing
          title: New or existing Ops/Cloud Manager project
          type: select_one
          default: ops_manager_new_project
          when: "repl{{ ConfigOptionEquals `ops_manager_deploy_or_existing` `ops_manager_existing`}}"
          items:
            - name: ops_manager_new_project
              title: Create a New Project
            - name: ops_manager_existing_project
              title: Use Existing Project

        - name: ops_manager_baseurl
          title: OpsManager Base URL
          type: text
          required: true
          when: "repl{{ ConfigOptionEquals `ops_manager_deploy_or_existing` `ops_manager_existing`}}"
          value: "https://cloud.mongodb.com"

        - name: mongo_project_name
          title: Project Name
          type: text
          when: "repl{{ ConfigOptionEquals `mongo_ops_manager_project_new_or_existing` `ops_manager_existing_project`}}"
          default: mongodb-enterprise-operator

        - name: mongo_ops_manager_org_new_or_existing
          title: New or existing Ops/Cloud Manager org
          type: select_one
          default: ops_manager_new_org
          when: "repl{{ ConfigOptionEquals `ops_manager_deploy_or_existing` `ops_manager_existing`}}"
          items:
            - name: ops_manager_new_org
              title: Create a New Org
            - name: ops_manager_existing_org
              title: Use Existing Org
        - name: mongo_org_id
          title: Organization ID
          type: text
          when: "repl{{ ConfigOptionEquals `mongo_ops_manager_org_new_or_existing` `ops_manager_existing_org`}}"

    - name: example_settings
      title: Mongo Configuration
      items:
        - name: ops_manager_pull_policy
          title: Pull Policy
          help_text: Image Pull Policy for Ops manager
          type: select_one
          default: Always
          items:
            - name: Always
              title: Always
            - name: IfNotPresent
              title: IfNotPresent
            - name: Never
              title: Never
    - name: initial_db
      title: Initial Database
      items:
        - name: create_mongo_db
          title: Create initial MongoDB database
          help_text: The Operator can automatically create a MongoDB instance to get you started
          type: bool
          default: "0"
        - name: initial_db_name
          title: Initial Database Name
          type: text
          required: true
          default: "mongodb-enterprise-database"
          when: "repl{{ ConfigOptionEquals `create_mongo_db` `1`}}"
        - name: initial_members_count
          title: Number of Replicas
          type: text
          default: "3"
          when: "repl{{ ConfigOptionEquals `create_mongo_db` `1`}}"
        - name: initial_version
          title: Version
          type: text
          default: "4.2.1"
          when: "repl{{ ConfigOptionEquals `create_mongo_db` `1`}}"
    - name: smtp_mail
      title: SMTP Mail Configuration
      items:
        - name: setup_smtp_mail
          title: Setup SMTP Mail configuration
          help_text: Setting up SMTP allows to you get emails from MongoDB
          type: bool
          default: "0"
        - name: smtp_mail_host
          title: Host
          type: text
          required: true
          default: "smtp.gmail.com"
          when: "repl{{ ConfigOptionEquals `setup_smtp_mail` `1`}}"
        - name: smtp_mail_username
          title: Username
          type: text
          required: true
          default: "example@server.com"
          when: "repl{{ ConfigOptionEquals `setup_smtp_mail` `1`}}"
        - name: smtp_mail_password
          title: Password
          type: password
          required: true
          default: "FOOFOOFOO"
          when: "repl{{ ConfigOptionEquals `setup_smtp_mail` `1`}}"
        - name: smtp_mail_port
          title: Port
          type: text
          required: true
          default: "587"
          when: "repl{{ ConfigOptionEquals `setup_smtp_mail` `1`}}"
